# Notes:
# the auto_show  property decides which panels open automatically.
# As a side effect, the gui renderering code for panels with auto_show=true will be precompiled while
# others will not.

[general]
    data_path = "/mnt/datadrive/DATA"

[[component]]
    type="ImageViewer"
    name = "Image Viewer"
 
[[component]]
    type="ImageViewer"
    name = "Image Viewer 2"
    auto_show = true

    
[[component]]
    type="ImageViewer"
    name = "Image Viewer 3"

[[component]]
    type = "ImageFeed"
    name = "GoldEye (uncalibrated)"
    input-channel = "aeron:ipc"
    input-stream = 1003
    auto_show = false

[[component]]
    type = "ImageFeed"
    name = "GoldEye"
    input-channel = "aeron:ipc"
    input-stream = 1013
    auto_show = true


[[component]]
    type="ImageFeed"
    name="CRED2 (uncalibrated)"
    input-channel="aeron:ipc"
    input-stream=1001
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]


[[component]]
    type="ImageFeed"
    name="IFTS (uncalibrated)"
    input-channel="aeron:ipc"
    input-stream=1006
    auto_show = true
    
[[component]]
    type="ImageFeed"
    name="IFTS"
    input-channel="aeron:ipc"
    input-stream=1016
    auto_show = true
    

[[component]]
    type="ImageFeed"
    name="CRED2"
    input-channel="aeron:ipc"
    input-stream=1011
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]

[[component]]
    type="ImageFeed"
    name="CRED2: Differential"
    input-channel="aeron:ipc"
    input-stream=5003
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]


[[component]]
    type="ImageFeed"
    name="CRED2: Un-Fringed"
    input-channel="aeron:ipc"
    input-stream=5001
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]



[[component]]
    type="ImageFeed"
    name="CRED2: Fringed"
    input-channel="aeron:ipc"
    input-stream=5002
    auto_show = true

    # crop = true
    # cropx = [147,467]
    # cropy = [67,387]

[[component]]
    type="DMFeed"
    name="LOWFS Residual"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=2001
    auto_show = true
    idle-timeout = 0.01


[[component]]
    type="DMFeed"
    name="LOWFS Prediction"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=9001
    auto_show = false
    idle-timeout = 0.01



[[component]]
    type="DMFeed"
    name="DM Mixer Output"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:udp?endpoint=localhost:20121"
    input-stream=1002
    auto_show = true
    idle-timeout = 1.0

[[component]]
    type="DMFeed"
    name="Calibration Offset"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=1005
    auto_show = true
    idle-timeout = 5.0

[[component]]
    type="DMFeed"
    name="User Offset"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=1007
    auto_show = true
    idle-timeout = 1e30 # never timeout

[[component]]
    type="DMFeed"
    name="SCC Residual"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=6000
    auto_show = true
    idle-timeout = 10.0

[[component]]
    type="DMFeed"
    name="Integrator Output"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    input-channel="aeron:ipc"
    input-stream=7000
    auto_show = true
    idle-timeout = 10.0


[[component]]
    type="DMOffsetTool"
    name="DM Offset Tool"
    zern-modes="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    lowfs-modes="/mnt/datadrive/DATA/LOWFS/modes-to-actus.fits"
    fourier-modes="/mnt/datadrive/DATA/SCC/modemat-all.fits"
    actuator-map="/mnt/datadrive/DATA/dm/BAX307-actu-map.fits"
    valid-actuator-map="/mnt/datadrive/DATA/dm/BAX307-valid-actu-map.fits"
    output-channel="aeron:ipc"
    output-stream=1007
    auto_show = true


[[component]]
    type="TTMonitor"
    name="LOWFS TT Monitor"
    modes-to-actus="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    history-length=850
    input-channel="aeron:ipc"
    input-stream=3001
    auto_show = false

[[component]]
    type="TTMonitor"
    name="LOWFS TT Residual"
    modes-to-actus="/mnt/datadrive/DATA/dm/zern-to-actus.fits"
    history-length=850
    input-channel="aeron:ipc"
    input-stream=2001
    auto_show = true


[[component]]
    name = "Integrator Control"
    type = "Integrator"
    url-scc = "http://localhost:8009"
    url-lowfs = "http://localhost:8008"
    url-integ = "http://localhost:8010"
    auto_show = false
